server:
  port: 8280
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: chartroom
  datasource:
    url: jdbc:mysql://localhost:3306/hands?serverTimezone=UTC
    username: root
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver
